services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/Dockerfile.backend
    ports:
      - "8000:8000"
    container_name: scanner_backend
    restart: always

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "80:80"
    container_name: scanner_frontend
    restart: always
    depends_on:
      - backend
