FROM python:3.11-slim

WORKDIR /app

# 🔥 Install nmap inside the container
RUN apt-get update && apt-get install -y nmap

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
